FOOTBALL_SCHEMA = {
    "type": "array",
    "items": {
        "type" : "object",
        "properties" : {
            "pid": {'type': 'string', 'pattern': '^[0-9]{10}$'},
            "meta": {
                "type": "object",
                "properties": {
                    'class': {'type': 'number', 'enum': [1,2,3,4,5]},
                    'conference': {'type': 'string'},
                    'date': {'type': 'string', 'pattern': '^[0-9]*$'}, # Unix time epoch (seconds since Jan 1, 1970)
                    'division': {'type': 'number', 'enum': [1,2,3]},
                    'first': {'type': 'string'},
                    'institution': {'type': 'string'},
                    'last': {'type': 'string'},
                    'position': {'type': 'string', 'enum': ['QB', 'WR', 'OL', 'RB', 'TE', 'C', 'OT', 'FB', 'DL', 'DT', 'DE', 'LB', 'DB', 'CB', 'S', 'P', 'K', 'LS']},
                    # include gender?
                    'sport': {'type': 'string', 'enum': ['Football', "Men's Basketball", "Women's Basketball", 'Baseball']},
                    'year': {'type':'string', 'pattern': '^[0-9]{2}-[0-9]{2}$'},
                },
                "additionalProperties": False,
                "required": [
                    "class",
                    "conference",
                    "date",
                    "division",
                    "first",
                    "last",
                    "position",
                    "sport",
                    "year",
                ],
            },
            "stats": {
                "type": "object",
                "properties": {
                    "general": {
                        "type": "object",
                        "properties": {
                            'all_purpose_plays': {'type': 'number'},
                            'all_purpose_yds': {'type': 'number'},
                            'all_purpose_yds_per_game': {'type': 'number'},
                            'games_played': {'type': 'number'},
                            'games_started': {'type': 'number'},
                            'points': {'type': 'number'},
                            'touchdowns': {'type': 'number'},
                        },
                        "additionalProperties": False,
                    },
                    "offensive": {
                        "type": "object",
                        "properties": {
                            'completion_pct': {'type': 'number'},
                            'completions_per_game': {'type': 'number'},
                            'first_downs': {'type': 'number'},
                            'first_downs_passing': {'type': 'number'},
                            'first_downs_rushing': {'type': 'number'},
                            'fumbles_lost': {'type': 'number'},
                            'interceptions': {'type': 'number'},
                            'pass_attempts': {'type': 'number'},
                            'passing_eff': {'type': 'number'},
                            'passing_tds': {'type': 'number'},
                            'passing_yds': {'type': 'number'},
                            'passing_yds_per_game': {'type': 'number'},
                            'penalties': {'type': 'number'},
                            'penalties_per_game': {'type': 'number'},
                            'penalty_yds': {'type': 'number'},
                            'penalty_yds_per_game': {'type': 'number'},
                            'plays': {'type': 'number'},
                            'receiving_longest': {'type': 'number'},
                            'receiving_tds': {'type': 'number'},
                            'receiving_yds': {'type': 'number'},
                            'receiving_yds_per_game': {'type': 'number'},
                            'receptions': {'type': 'number'},
                            'receptions_per_game': {'type': 'number'},
                            'redzone_attempts': {'type': 'number'},
                            'redzone_passing_tds': {'type': 'number'},
                            'redzone_pts': {'type': 'number'},
                            'redzone_rushing_tds': {'type': 'number'},
                            'redzone_scores': {'type': 'number'},
                            'rush_attempts': {'type': 'number'},
                            'rush_net_yds': {'type': 'number'},
                            'rush_yds_per_game': {'type': 'number'},
                            'rushing_longest': {'type': 'number'},
                            'rushing_tds': {'type': 'number'},
                            'rushing_yds': {'type': 'number'},
                            'rushing_yds_lost': {'type': 'number'},
                            'third_att': {'type': 'number'},
                            'third_conv': {'type': 'number'},
                            'total_offensive_plays': {'type': 'number'},
                            'total_offensive_yds': {'type': 'number'},
                            'total_offensive_yds_per_game': {'type': 'number'},
                            'total_offensive_yds_per_play': {'type': 'number'},
                            'yds': {'type': 'number'},
                            'yds_per_completion': {'type': 'number'},
                            'yds_per_play': {'type': 'number'},
                            'yds_per_reception': {'type': 'number'},
                            'yds_per_rush': {'type': 'number'},
                        },
                        "additionalProperties": False,
                    },
                    "defensive": {
                        "type": "object",
                        "properties": {
                            'blocked': {'type': 'number'},
                            'fumbles_forced': {'type': 'number'},
                            'fumbles_recovered': {'type': 'number'},
                            'fumbles_returned': {'type': 'number'},
                            'fumbles_returned_tds': {'type': 'number'},
                            'interception_yds': {'type': 'number'},
                            'interceptions': {'type': 'number'},
                            'interceptions_returned_tds': {'type': 'number'},
                            'pass_breakups': {'type': 'number'},
                            'passes_defended': {'type': 'number'},
                            'pts_off_turnover': {'type': 'number'},
                            'redzone_end_downs': {'type': 'number'},
                            'redzone_end_interceptions': {'type': 'number'},
                            'sack_yds': {'type': 'number'},
                            'sacks_assisted': {'type': 'number'},
                            'sacks_solo': {'type': 'number'},
                            'sacks_unassisted': {'type': 'number'},
                            'safeties': {'type': 'number'},
                            'tackle_yds': {'type': 'number'},
                            'tackles': {'type': 'number'},
                            'tackles_assisted': {'type': 'number'},
                            'tackles_for_loss_assisted': {'type': 'number'},
                            'tackles_for_loss_solo': {'type': 'number'},
                            'tackles_solo': {'type': 'number'},
                        },
                        "additionalProperties": False,
                    },
                    "special": {
                        "type": "object",
                        "properties": {
                            'fc_yds': {'type': 'number'},
                            'fga1_19': {'type': 'number'},
                            'fga20_29': {'type': 'number'},
                            'fga30_39': {'type': 'number'},
                            'fga40_49': {'type': 'number'},
                            'fga50_59': {'type': 'number'},
                            'fga60': {'type': 'number'},
                            'fgm1_19': {'type': 'number'},
                            'fgm20_29': {'type': 'number'},
                            'fgm30_39': {'type': 'number'},
                            'fgm40_49': {'type': 'number'},
                            'fgm50_59': {'type': 'number'},
                            'fgm60': {'type': 'number'},
                            'field_goal_blocks_allowed': {'type': 'number'},
                            'field_goals': {'type': 'number'},
                            'field_goals_attempted': {'type': 'number'},
                            'field_goals_made': {'type': 'number'},
                            'fumble_return_pat': {'type': 'number'},
                            'kick_pat': {'type': 'number'},
                            'kick_return_pat': {'type': 'number'},
                            'kickoff_return_tds': {'type': 'number'},
                            'kickoff_return_yds': {'type': 'number'},
                            'kickoff_returns': {'type': 'number'},
                            'kickoff_touchbacks': {'type': 'number'},
                            'kickoff_yds': {'type': 'number'},
                            'kickoffs': {'type': 'number'},
                            'longest_fgm': {'type': 'number'},
                            'net_kickoff_yds': {'type': 'number'},
                            'net_punt_yds': {'type': 'number'},
                            'onside_attempts': {'type': 'number'},
                            'pass_2pt_att': {'type': 'number'},
                            'pass_2pt_conv': {'type': 'number'},
                            'pat_att': {'type': 'number'},
                            'punt_longest': {'type': 'number'},
                            'punt_return_tds': {'type': 'number'},
                            'punt_return_yds': {'type': 'number'},
                            'punt_returns': {'type': 'number'},
                            'punt_touchbacks': {'type': 'number'},
                            'punt_yds': {'type': 'number'},
                            'punts': {'type': 'number'},
                            'punts_inside_twenty': {'type': 'number'},
                            'receiving_pat': {'type': 'number'},
                            'redzone_end_field_goal': {'type': 'number'},
                            'redzone_end_fumble': {'type': 'number'},
                            'redzone_fg_made': {'type': 'number'},
                            'rush_2pt_att': {'type': 'number'},
                            'rush_pat': {'type': 'number'},
                            'successful_onside_kicks': {'type': 'number'},
                        },
                        "additionalProperties": False,
                    },
                },
                "additionalProperties": False,
                "required": [
                    "general",
                    "offensive",
                    "defensive",
                    "special",
                ],
            },
        },
        "additionalProperties": False,
        "required" : [
            "meta",
            "stats",
            "pid",
        ],
    }
}
